<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Config.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="UI_func.fs" />
    <Compile Include="StartMenu_Interaction.fs" />
    <Compile Include="Shake.fs" />
    <Compile Include="GuageBar.fs" />
    <Compile Include="Name.fs" />
    <Compile Include="ReturnMenuUI.fs" />
    <Compile Include="GamePause_Interaction.fs" />
    <Compile Include="ReturnMenu_Interaction.fs" />
    <Compile Include="Dice_Interaction.fs" />
    <Compile Include="Turn_Manager.fs" />
    <Compile Include="Table_Interaction.fs" />
    <Compile Include="Game_Interaction.fs" />
    <Compile Include="Interaction.fs" />
    <Compile Include="StartMenuUI.fs" />
    <Compile Include="DiceUI.fs" />
    <Compile Include="TableUI.fs" />
    <Compile Include="BoardUI.fs" />
    <Compile Include="Drawing.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
  </ItemGroup>

</Project>
